name: Bug
description: Errors in the application or relevant systems.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! Your feedback helps us improve the app.
  - type: input
    id: device-info
    attributes:
      label: Device Information
      description: Make and model of the mobile device, and OS version (e.g., iPhone 12, iOS 16.2 or Samsung Galaxy S21, Android 12).
      placeholder: e.g., iPhone 12, iOS 16.2
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Which version of the app are you using? You can find this in the settings.
      placeholder: e.g., 1.2.3
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Network Type
      description: Was the issue occurring over Wi-Fi, mobile data, or offline?
      placeholder: e.g., Wi-Fi, 5G, offline
      options:
        - Wi-Fi 
        - 5G
        - offline
      default: 0
    validations:
      required: true
  - type: input
    id: battery
    attributes:
      label: Battery State
      description: Was your device low on battery? (Yes/No)
      placeholder: Yes/No
    validations:
      required: false
  - type: input
    id: screen-orientation
    attributes:
      label: Screen Orientation
      description: Was the app in portrait or landscape mode when the issue occurred?
      placeholder: e.g., Portrait
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. On this Page...
        2. With this Phone...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots or recordings that give us more context about the issue you are encountering!
        
        Tip: Attach images, screen recordings, or log files by dragging them here.
    validations:
      required: false
